language: php
sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - SYMFONY_CONSOLE_VERSION=~2.3.6
    - SYMFONY_CONSOLE_VERSION=2.4.*
    - SYMFONY_CONSOLE_VERSION=2.5.*
    - SYMFONY_CONSOLE_VERSION=2.6.*
    - SYMFONY_CONSOLE_VERSION=2.7.*@dev
    - SYMFONY_CONSOLE_VERSION=3.0.*@dev

matrix:
    fast_finish: true
    allow_failures:
        - env: SYMFONY_CONSOLE_VERSION=2.7.*@dev
        - env: SYMFONY_CONSOLE_VERSION=3.0.*@dev

cache:
    directories:
        - $COMPOSER_CACHE_DIR

before_script:
    - "[[ \"$SYMFONY_CONSOLE_VERSION\" = '3.0.*@dev' && -z \"$(php -v | grep -E '5.[5-6]')\" ]] && true || composer require --prefer-source --dev symfony/console:${SYMFONY_CONSOLE_VERSION}"
    - "[[ \"$SYMFONY_CONSOLE_VERSION\" = '3.0.*@dev' && -z \"$(php -v | grep -E '5.[5-6]')\" ]] && true || composer install"

script:
    - "[[ \"$SYMFONY_CONSOLE_VERSION\" = '3.0.*@dev' && -z \"$(php -v | grep -E '5.[5-6]')\" ]] && true || bin/atoum"
    - "[[ \"$SYMFONY_CONSOLE_VERSION\" = '3.0.*@dev' && -z \"$(php -v | grep -E '5.[5-6]')\" ]] && true || bin/console"
